name: Runner Smoke Test for testing the connectivity

on:
  push:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Hostname
        run: hostname

      - name: User
        run: whoami

      - name: Directory
        run: pwd